### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by fflorent**
## Problem

- Take into account remarks from code review

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by fflorent** [comment]
!testme

**Comment by alexAubin** [comment]
Test is looking good ! Level 0 seems to be only related to the app not being in the catalog ;) Otherwise probably already level 6~7

Only thing I can find with a quick look is at the end of the upgrade:

>Error: Apparently the log is telling that 'some file got manually modified' ... which should not happen, considering that no human modified the file ... ! Maybe you need to check what's happening with ynh_store_file_checksum and ynh_backup_if_checksum_is_different between install and upgrade.

which is related to the fact that `run.sh` gets deleted/overwritten during the `ynh_setup_source` here: https://github.com/YunoHost-Apps/matrix-puppet-discord_ynh/blob/testing/scripts/upgrade#L113

There's [a small option for `ynh_setup_source` which should help with this](https://yunohost.org/packaging_apps_helpers#ynh_setup_source): `--keep="$final_path/run.sh"` which will temporarily backup the file, and therefore the file won't appeared as manually modified

(It's quite mysterious and technical if you're not familiar with it, but basically `ynh_add_config` computes and saves a checksum, and will complain when trying to overwrite a file whose checksum got modified since the last writing, i.e. the app appears as if it got manually modified by the user)

**Comment by fflorent** [comment]
Thanks for your look!

> Level 0 seems to be only related to the app not being in the catalog ;) Otherwise probably already level 6~7

Alright! PR created then: https://github.com/YunoHost/apps/pull/1239

> There's a small option for ynh_setup_source which should help with this: --keep="$final_path/run.sh" which will temporarily backup the file, and therefore the file won't appeared as manually modified

Thanks for your hint!

**Comment by fflorent** [comment]
!testme

**Comment by fflorent** [comment]
!testme

**Pull request merged**
