### PR TITLE
Make npm install works with no error

### PR DESCRIPTION
**Pull request by rosbeef**
## Problem

- install fail due to npm version not mactching

## Solution

- user ynh helper $ynh_npm 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by rosbeef** [comment]
modifiing command line with $ynh_npm does notwork

changing node to v12.0.0 (npm to 6.9.0) does not work 
https://paste.yunohost.org/raw/givoxeleyo

last node version v14 with npm 6.x.x does not work
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2.

**Comment by fflorent** [comment]
!testme

**Comment by fflorent** [comment]
Fixed with #12

**Comment by rosbeef** [comment]
Not working on armv7l
https://paste.yunohost.org/raw/ubegeqazuz

**Comment by fflorent** [comment]
You seem to install version `0.1.7~ynh3` but it should be `0.1.7~ynh4`

**Pull request closed without merging**
